"$schema" = 'https://starship.rs/config-schema.json'
format="""
[┌──](bold green) $time$directory\
$terraform\
$kubernetes\
$docker_context\
$helm\
$vagrant$fill
[│](bold green) $username$hostname$shlvl\
$singularity\
$vcsh\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$zig\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$openstack\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
[│](bold green) $git_branch$git_commit$git_state$git_metrics$git_status$hg_branch\
$fill\
$aws$gcloud$azure
[└─](bold green)$character """
right_format="""
"""

[username]
style_user = "white bold"
style_root = "red bold"
format = "as [$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@](bold blue)[$ssh_symbol](bold blue)[$hostname](bold red) "
trim_at = "."
disabled = false

[gcloud]
format = 'in [$symbol$project]($style) '

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "10:00:00-14:00:00"

[conda]
ignore_base = false

[fill]
symbol=" "

